bases:
  - github.com/binkhq/postgres-to-azureblob/deploy


patches:
  - target:
      kind: CronJob
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "30 * * * *"
  - target:
      kind: CronJob
    patch: |-
      - op: replace
        path: /metadata/name
        value: postgres-to-azureblob-example
  - target:
      kind: CronJob
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env
        value:
          - name: blob_storage_connection_string
            valueFrom:
              secretKeyRef:
                key: connection_string
                name: azure-storage-common
          - name: blob_storage_container
            value: backups
          - name: blob_storage_path_prefix
            value: hourly
          - name: psql_connection_string
            valueFrom:
              secretKeyRef:
                key: common_postgres
                name: azure-pgfs
