name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      blob_storage_connection_string: ${{ secrets.BLOB_STORAGE_DSN }}
      blob_storage_container: github
      blob_storage_path_prefix: repo/postgres-to-azureblob
      psql_connection_string: postgresql://postgres@127.0.0.1/postgres
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: pip install pipenv
      - run: pipenv install --dev --system --deploy --ignore-pipfile
      - run: flake8 .
      - run: black --line-length=120 --check .
      - run: isort --check --line-length 120 --profile black .
      - run: curl -L https://github.com/credativ/omdb-postgresql/releases/download/2021-11-09/omdb.dump -o omdb.dump
      - run: pg_restore --host=127.0.0.1 --username=postgres --dbname=postgres omdb.dump      
      - run: python main.py
  build:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: build
    runs-on: ubuntu-latest
    needs: [ tests ]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - run: echo "::set-output name=date::$(date +'%FT%H%M%SZ')"
      id: date
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/binkhq/postgres-to-azureblob:${{ steps.date.outputs.date }}
          ghcr.io/binkhq/postgres-to-azureblob:latest
